Repository mandamong/swift-ios-mandamong, pull requests merged in 2025-09, with the labels that each got.

#6 [Chore] Apply Custom Fonts
  Projects/Shared/Resources/DesignSystem/Fonts/SpoqaHanSansNeo-Bold.otf
  Projects/Shared/Resources/DesignSystem/Fonts/SpoqaHanSansNeo-Medium.otf
  Projects/Shared/Resources/DesignSystem/Fonts/SpoqaHanSansNeo-Regular.otf
  Projects/Shared/Resources/mt.swift
  Projects/Shared/Sources/Extensions/SwiftUI/Font.swift
  Projects/Shared/Sources/mt.swift
  Tuist/.build/workspace-state.json
Labels: :wastebasket: chore, :beers: swain

#8 [Chore] 깃 추적 방지 재설정 및 불필요한 파일 삭제
  .DS_Store
  Derived/InfoPlists/Domain-Info.plist
  Derived/InfoPlists/Infrastructure-Info.plist
  Derived/InfoPlists/Mandamong-Info.plist
  Derived/InfoPlists/MandamongTests-Info.plist
  Derived/InfoPlists/Presentation-Info.plist
  Derived/InfoPlists/Repository-Info.plist
  Derived/Sources/TuistAssets+Mandamong.swift
  Derived/Sources/TuistBundle+Mandamong.swift
  Derived/Sources/TuistFonts+Mandamong.swift
  Mandamong.xcodeproj/project.pbxproj
  Mandamong.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  Mandamong.xcodeproj/project.xcworkspace/xcuserdata/swain.xcuserdatad/UserInterfaceState.xcuserstate
  Mandamong.xcodeproj/xcshareddata/xcschemes/Domain.xcscheme
  Mandamong.xcodeproj/xcshareddata/xcschemes/Infrastructure.xcscheme
  Mandamong.xcodeproj/xcshareddata/xcschemes/Mandamong.xcscheme
  Mandamong.xcodeproj/xcshareddata/xcschemes/Presentation.xcscheme
  Mandamong.xcodeproj/xcshareddata/xcschemes/Repository.xcscheme
  Mandamong.xcodeproj/xcuserdata/swain.xcuserdatad/xcschemes/xcschememanagement.plist
  Mandamong.xcworkspace/.tuist-generated
  Mandamong.xcworkspace/contents.xcworkspacedata
  Mandamong.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
  Mandamong.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Mandamong.xcworkspace/xcshareddata/xcschemes/Mandamong-Workspace.xcscheme
  Mandamong.xcworkspace/xcuserdata/swain.xcuserdatad/UserInterfaceState.xcuserstate
  Mandamong.xcworkspace/xcuserdata/swain.xcuserdatad/xcschemes/xcschememanagement.plist
  Mandamong/.DS_Store
  Mandamong/Application/Assets.xcassets/AccentColor.colorset/Contents.json
  Mandamong/Application/Assets.xcassets/AppIcon.appiconset/Contents.json
  Mandamong/Application/Assets.xcassets/Contents.json
  Mandamong/Application/MandamongApp.swift
  Mandamong/Presentation/ContentView.swift
  Mandamong/Resources/.DS_Store
  Mandamong/Sources/.DS_Store
  Tuist/.build/workspace-state.json
Labels: :wastebasket: chore, :construction_worker: jinung

#13 [Setting] Shared 하위 타겟으로 분리
  Projects/App/Project.swift
  Projects/Login/LoginData/Project.swift
  Projects/Login/LoginDomain/Project.swift
  Projects/Login/LoginFeature/Project.swift
  Projects/Mandarat/MandaratData/Project.swift
  Projects/Mandarat/MandaratDomain/Project.swift
  Projects/Mandarat/MandaratFeature/Project.swift
  Projects/Shared/DesignSystem/Resources/Fonts/SpoqaHanSansNeo-Bold.otf
  Projects/Shared/DesignSystem/Resources/Fonts/SpoqaHanSansNeo-Medium.otf
  Projects/Shared/DesignSystem/Resources/Fonts/SpoqaHanSansNeo-Regular.otf
  Projects/Shared/DesignSystem/Sources/Color.swift
  Projects/Shared/DesignSystem/Sources/Font.swift
  Projects/Shared/Project.swift
  Projects/Shared/Utils/Sources/Empty.swift
Labels: :building_construction: setting, :construction_worker: jinung

#16 [Feat] API별 Endpoint, 필요 DTO 추가
  Projects/Login/LoginData/Sources/DTO/CheckEmailDuplicationDTO.swift
  Projects/Login/LoginData/Sources/DTO/CheckNicknameDuplicationDTO.swift
  Projects/Login/LoginData/Sources/DTO/EmailAuthenticationCodeDTO.swift
  Projects/Login/LoginData/Sources/DTO/LoginDTO.swift
  Projects/Login/LoginData/Sources/DTO/RegisterDTO.swift
  Projects/Login/LoginData/Sources/DTO/ReissueTokenDTO.swift
  Projects/Login/LoginData/Sources/DTO/ResetPasswordDTO.swift
  Projects/Login/LoginData/Sources/DTO/UpdateProfileDTO.swift
  Projects/Login/LoginData/Sources/DTO/ValidatePasswordDTO.swift
  Projects/Login/LoginData/Sources/DTO/VerifyEmailDTO.swift
  Projects/Login/LoginData/Sources/Endpoint.swift
  Projects/Login/LoginData/Sources/mt.swift
  Projects/Mandarat/MandaratData/Sources/DTO/CreateActionsByObjective.swift
  Projects/Mandarat/MandaratData/Sources/DTO/CreateMandaratBySubjectDTO.swift
  Projects/Mandarat/MandaratData/Sources/DTO/ReusableDTO.swift
  Projects/Mandarat/MandaratData/Sources/DTO/SaveMandaratDTO.swift
  Projects/Mandarat/MandaratData/Sources/DTO/UpdateActionStatusDTO.swift
  Projects/Mandarat/MandaratData/Sources/DTO/UpdateMandaratActionDTO.swift
  Projects/Mandarat/MandaratData/Sources/DTO/UpdateMandaratObjectiveDTO.swift
  Projects/Mandarat/MandaratData/Sources/DTO/UpdateMandaratSubjectDTO.swift
  Projects/Mandarat/MandaratData/Sources/DTO/UpdateMandaratTitleDTO.swift
  Projects/Mandarat/MandaratData/Sources/Endpoint.swift
  Projects/Mandarat/MandaratData/Sources/mt.swift
  Projects/Network/Sources/ResponseDTO.swift
  Projects/Network/Sources/mt.swift
Labels: :sparkles: feat, :beers: swain

#18 [Feat] Implement Keychain Storage
  Projects/Network/Sources/KeychainStorage.swift
Labels: :sparkles: feat, :beers: swain

#20 [Feat] Add Token Model
  Projects/Network/Sources/Tokens.swift
Labels: :sparkles: feat, :beers: swain

#22 [Feat] Alamofire 기반 네트워킹 객체 구현
  Projects/Network/Project.swift
  Projects/Network/Sources/APIEndpoint.swift
  Projects/Network/Sources/DTOs/ResponseDTO.swift
  Projects/Network/Sources/Errors/NetworkError.swift
  Projects/Network/Sources/Errors/RequestError.swift
  Projects/Network/Sources/Errors/ResponseError.swift
  Projects/Network/Sources/Keychain/KeychainStorage.swift
  Projects/Network/Sources/NetworkService.swift
  Projects/Network/Sources/ResponseDTO.swift
  Projects/Network/Sources/Utils/NetworkLogger.swift
  Projects/Network/Sources/Utils/TokenInterceptor.swift
  Projects/Network/Sources/Utils/Tokens.swift
  Tuist/Package.resolved
  Tuist/Package.swift
Labels: :sparkles: feat, :construction_worker: jinung

#24 [Feat] 만다라트 주요 도메인 모델 추가
  Projects/Mandarat/MandaratDomain/Sources/Entities/Mandarat.swift
  Projects/Mandarat/MandaratDomain/Sources/mt.swift
Labels: :sparkles: feat, :beers: swain

#30 [Setting] DesignSystem 모듈 연결
  Projects/App/Sources/MandamongApp.swift
  Projects/App/Sources/mt.swift
  Projects/Login/LoginFeature/Project.swift
  Projects/Mandarat/MandaratFeature/Project.swift
Labels: :building_construction: setting, :beers: swain
